name: Publish to GCR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_SECRET }}
      - name: Build and Push Docker Image
      - run: echo "Building and pushing Docker image...${{ github.repository_owner }}"
      - uses: docker/build-push-action@v4
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/esp32-camera-server:latest
          file: ./Backend/Dockerfile


