name: Publish to GCR

on:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1
          file: ./Backend/Dockerfile
          build-args: |
            GIT_SHA=${{ github.sha }} 
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VERSION=0.0.1

      - name: Verify Image Push
        run: |
          docker pull ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1
          docker images | grep esp32-camera-server
          docker run --rm ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1 python --version
          docker run --rm ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1 ls /app
          docker run --rm ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1 ls /data
          docker run --rm ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1 env
          docker run --rm -p 8080:8080 ghcr.io/barabasistvanattila/esp32-camera-server:0.0.1 curl -I http://localhost:8080/health || true
        
          